services:
    # image project
    app:
        build:
            context: ./app
        command: sh -c "npm ci && npm run build && npm run start:prod_db"
        restart: unless-stopped
        container_name: truco2-api-app-devel
        volumes:
            - ./app:/app/
        networks:
            - appnet
        depends_on:
            - postgres
    
    nginx:
        restart: unless-stopped
        container_name: truco2-api-nginx-devel
        build:
            context: ./nginx
        ports:
            - "8116:80"
        networks:
            - appnet
        depends_on:
            - app

    postgres:
        image: postgres:15
        restart: unless-stopped
        container_name: truco2-api-postgres-devel
        environment:
            POSTGRES_PASSWORD: truco123
        volumes:
            - ./psql:/var/lib/postgresql/data
        networks:
            - appnet
        ports:
            - "5532:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        container_name: truco2-api-pgadmin-devel
        environment:
            PGADMIN_DEFAULT_EMAIL: truco2.user@ufam.com.br
            PGADMIN_DEFAULT_PASSWORD: truco123
        ports:
            - "16643:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - appnet

networks:
    appnet:
        driver: bridge