services:
    # image project
    app:
        build:
            context: ./app
        command: sh -c "npm install && npm run test:e2e_db"
        restart: unless-stopped
        container_name: truco2-api-app
        env_file:
            - ./app/.env.example
        networks:
            - appnet
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        restart: unless-stopped
        container_name: truco2-api-postgres
        environment:
            POSTGRES_PASSWORD: truco123
        networks:
            - appnet

networks:
    appnet:
        driver: bridge