services:
    # image project
    app:
        build:
            context: ./app
        command: sh -c "npm install && npm run build && npm run start:prod"
        restart: unless-stopped
        container_name: truco2-api-app
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app/
        networks:
            - appnet
        depends_on:
            - postgres
    
    nginx:
        restart: unless-stopped
        container_name: truco2-api-nginx
        build:
            context: ./nginx
        ports:
            - "8016:80"
        networks:
            - appnet
        depends_on:
            - app

    postgres:
        image: postgres:15
        restart: unless-stopped
        container_name: truco2-api-postgres
        environment:
            POSTGRES_PASSWORD: truco123
        volumes:
            - ./psql:/var/lib/postgresql/data
        networks:
            - appnet
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        container_name: truco2-api-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: truco2.user@ufam.com.br
            PGADMIN_DEFAULT_PASSWORD: truco123
        ports:
            - "16543:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - appnet

networks:
    appnet:
        driver: bridge