version: "3.8"

services:
    # image project
    app:
        build:
            context: ./app
        command: sh -c "npm install && npm run start"
        restart: unless-stopped
        container_name: truco2-api-app
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app/
        networks:
            - appnet
    
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8016:80"
        networks:
            - appnet
        depends_on:
            - app
    
networks:
    appnet:
        driver: bridge