services:
    # image project
    app:
        build:
            context: ./app
        command: sh -c "npm install && npm run start:dev_db"
        restart: unless-stopped
        container_name: truco2-api-app-staging
        ports:
            - "3200:3000"
        volumes:
            - ./app:/app/
        networks:
            - appnet
        depends_on:
            - postgres
    
    nginx:
        restart: unless-stopped
        container_name: truco2-api-nginx-staging
        build:
            context: ./nginx
        ports:
            - "8216:80"
        networks:
            - appnet
        depends_on:
            - app

    postgres:
        image: postgres:15
        restart: unless-stopped
        container_name: truco2-api-postgres-staging
        environment:
            POSTGRES_PASSWORD: truco123
        volumes:
            - ./psql:/var/lib/postgresql/data
        networks:
            - appnet
        ports:
            - "5632:5432"

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        container_name: truco2-api-pgadmin-staging
        environment:
            PGADMIN_DEFAULT_EMAIL: truco2.user@ufam.com.br
            PGADMIN_DEFAULT_PASSWORD: truco123
        ports:
            - "16743:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - appnet

networks:
    appnet:
        driver: bridge