#CD GitHub Actions Workflow
name: Truco 2 API VPS CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 80
        script: |
          cd ~/home/dev/truco2-api/
          git pull origin main
          docker compose up -d --build
