#CD GitHub Actions Workflow
name: CI/CD

on:
  push:
    branches: [devel, staging, main]
  pull_request:
    branches: [devel, staging, main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Unit Tests
        working-directory: ./app
        run: npm ci && npm run test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: E2E Tests
        run: docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit --exit-code-from app
  deploy-devel:
    if: github.ref_name == 'devel'
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/truco2-api-devel/
            git pull origin devel
            sh deply.sh "devel" "${{ vars.API_DEVEL_PORT }}" "postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ secrets.SERVER_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_DEVEL }}?schema=public" "${{ secrets.API_JWT_SECRET }}"
  deploy-staging:
    if: github.ref_name == 'staging'
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/truco2-api-staging/
            git pull origin staging
            sh deply.sh "staging" "${{ vars.API_STAGING_PORT }}" "postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ secrets.SERVER_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_STAGING }}?schema=public" "${{ secrets.API_JWT_SECRET }}"
  deploy-production:
    if: github.ref_name == 'main'
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/truco2-api/
            git pull origin main
            sh deply.sh "production" "${{ vars.API_PRODUCTION_PORT }}" "postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ secrets.SERVER_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_PRODUCTION }}?schema=public" "${{ secrets.API_JWT_SECRET }}"
