#CD GitHub Actions Workflow
name: staging

on:
  push:
    branches: [staging]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Unit Tests
        working-directory: ./app
        run: npm ci && npm run test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: E2E Tests
        run: docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit --exit-code-from app
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/truco2-api-staging/
            git pull origin staging
            docker compose -f docker-compose.staging.yml up -d --build
